#!/bin/bash
docker run --rm \
  -v $(pwd)/docs:/out \
  -v $(pwd):/protos \
  pseudomuto/protoc-gen-doc \
  --doc_opt=markdown,api-services.md

# docker volumes create files as root
# chowning seems easier than modifiying the container to try to line up user ids
# https://stackoverflow.com/questions/27925006/share-files-between-host-system-and-docker-container-using-specific-uid
sudo chown -R $(whoami):$(whoami) ./docs
